[app-server]
35.183.178.2 ansible_user=ec2-user ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/wood.pem

[centos-node]
35.182.32.110 ansible_user=fedora ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/wood.pem

[debian-node]
3.96.194.39 ansible_user=admin ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/wood.pem

