plugin: aws_ec2
regions:
  - ca-central-1
filters:
  tag:Environment: flask
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address
  ansible_user: |
    {%- if 'debian' in tags.Name|lower -%}
    admin
    {%- elif 'centos' in tags.Name|lower -%}
    fedora
    {%- elif 'ubuntu' in tags.Name|lower -%}
    ubuntu
    {%- else -%}
    ec2-user
    {%- endif -%}
